name: 🐞 Bug Report
description: Report a reproducible bug
title: "[BUG]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
        Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clearly describe the bug.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Traceback
      description: Paste relevant logs or error messages.
      render: shell

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, Python version, etc.
      placeholder: macOS, Python 3.11