name: ✨ Feature Request
description: Suggest an idea or improvement
title: "[FEATURE]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!
        Please explain the problem before the solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions you've thought about?

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: This feature aligns with project goals
        - label: I am willing to work on this feature